[2024-05-06T04:54:47.823+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-06T04:54:47.850+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_complex.delete_entry manual__2024-05-06T04:53:55.730459+00:00 [queued]>
[2024-05-06T04:54:47.857+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_complex.delete_entry manual__2024-05-06T04:53:55.730459+00:00 [queued]>
[2024-05-06T04:54:47.858+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-06T04:54:47.873+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): delete_entry> on 2024-05-06 04:53:55.730459+00:00
[2024-05-06T04:54:47.883+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_complex', 'delete_entry', 'manual__2024-05-06T04:53:55.730459+00:00', '--job-id', '38', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_complex.py', '--cfg-path', '/tmp/tmpjq0fyz07']
[2024-05-06T04:54:47.886+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask delete_entry
[2024-05-06T04:54:47.894+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2673) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-06T04:54:47.895+0000] {standard_task_runner.py:63} INFO - Started process 2700 to run task
[2024-05-06T04:54:47.932+0000] {task_command.py:426} INFO - Running <TaskInstance: example_complex.delete_entry manual__2024-05-06T04:53:55.730459+00:00 [running]> on host 0cea9ba68f60
[2024-05-06T04:54:48.008+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_complex' AIRFLOW_CTX_TASK_ID='delete_entry' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T04:53:55.730459+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T04:53:55.730459+00:00'
[2024-05-06T04:54:48.010+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-06T04:54:48.011+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-06T04:54:48.011+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo delete_entry']
[2024-05-06T04:54:48.025+0000] {subprocess.py:86} INFO - Output:
[2024-05-06T04:54:48.027+0000] {subprocess.py:93} INFO - delete_entry
[2024-05-06T04:54:48.028+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-06T04:54:48.028+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-06T04:54:48.053+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=example_complex, task_id=delete_entry, execution_date=20240506T045355, start_date=20240506T045447, end_date=20240506T045448
[2024-05-06T04:54:48.112+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-06T04:54:48.126+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-06T04:54:48.133+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
